### ISSUE TITLE
cannot enable the add-on

### ISSUE THREAD

**Issue by sanzoghenzo** [CreativeDesigner3D/home_builder#1]
Hi, first of all thank you for this great tool!

I just tried to install the First Beta Release, but when I tried to activate it blender shows an error saying it cannot find the `~/.config/blender/3.4/scripts/addons/home_builder-3` path. 

The folder was indeed named as the zip file `home_builder-3.0.2`, and after removing the `.0.2` it worked well!

I don't know if it's a blender limitation or something in your code, but it seems that the dot character in the folder name is not supported/handled properly.

**Comment by TomasHubelbauer** [comment]
Hi! I also had an error when attempting to enable the add-on after installing it. I am not sure if it is the same issue as yours. Are you on macOS? If so, this might be worth trying: Andrew helped me on Discord and pointed me to this build:
https://creativedesigner3d.files.wordpress.com/2023/03/home_builder3_3.zip

For me it fixed the issues, hopefully it works for you as well!

**Comment by sanzoghenzo** [comment]
Hi, thanks for the feedback. As I stated in the issue, the build runs fine if you rename the zip file to `home_builder-3.zip`, so I already fixed my problem. 

This issue is just a heads-up to @CreativeDesigner3D to replace the dots in zip file name in future releases, so that there's no renaming needed.

[Here](https://blenderartists.org/t/the-installed-addon-is-not-in-the-list-of-addons/1189308)'s one proof that the dots in the file name (and thus in the expanded folder) are the culprit.

**Comment by TomasHubelbauer** [comment]
I see, okay! I'll admit I didn't read your message thoroughly so my comment wasn't too applicable. Sorry for that 😌

**Comment by CreativeDesigner3D** [comment]
@sanzoghenzo When I release a new version I change the file name to not include dots. When downloading from Github it automatically includes them. I am not sure how to change that functionality on github.

**Comment by sanzoghenzo** [comment]
Oh, it makes sense... I am subscribed to the github releases and didn't check your website...

You're right that github release names cannot be changed, so I guess we have to live with that :sweat_smile: 

Thanks again for all your work!
