### ISSUE TITLE
Error on enabling plugin

### ISSUE THREAD

**Issue by mahdiar** [CreativeDesigner3D/home_builder#11]
Hi
Very nice addon thanks.
I install blender 4.2.3 LTS and install addon 3.0.7. I can't enable it. it show this error:
"no module named 'home_builder-3'"

**Comment by CreativeDesigner3D** [comment]
If you are using Blender 4 you need to use home builder 4 https://github.com/CreativeDesigner3D/home_builder_4. You can download the add-on from here. https://creativedesigner3d.github.io/home_builder_3_docs/01_getting_started/

**Comment by mahdiar** [comment]
Thanks I try the 4th version and it shows that error
 "no module named 'home_builder-4'"

**Comment by CreativeDesigner3D** [comment]
Are you downloading from github? Try downloading from the official download. Github automatically adds a - to the file name which Blender doesn't like.
