### ISSUE TITLE
Broken behavior for the doors swing after reopenig blender project.

### ISSUE THREAD

**Issue by subiron** [CreativeDesigner3D/home_builder#2]
Home Builder Version 3.0.7 BETA
Blender Version 3.6.0 (3.6.0 2023-06-27)

Steps to reproduce:

- create wall and add a doors
- Using "doors prompts" dialog  set "open door" to eg 50%
- Save  bleder project and close blender
- Run blender and open saved project.

Actuaal bahavior:
- 'Doors swing' geometry is shifted and not rotated for all the doors in the scene.(see screenhot and project file)
- Any changes to the "doors swing " in "doors prompts" dialog are not working anymore.

<img width="932" alt="image" src="https://github.com/CreativeDesigner3D/home_builder/assets/462888/33757424-4ef1-4353-ad1f-2000e2ca5275">

sample project:
https://drive.google.com/file/d/1rJSBhgaiJxo0QNdJq6h83KZyCJHHpjSK/view?usp=sharing

**Comment by CreativeDesigner3D** [comment]
Thanks for the report. The issue is the image. Home Builder tries to evaluate the drivers for the entire scene, but i have an error that is not expecting an image empty. I will get this fixed for the 3.0.8 release, but for now delete the image floor plan object then save and reopen the file.

**Comment by subiron** [comment]
Thanks, it works now!

Also a tip if someone is struggling with FBX export from Blender because you have extra geometry in place of doors and windows when imported eg into UnrealEngine.
Because doors and windows are using boolean modifiers you must use settings below to export 'valid' geometry only

<img width="274" alt="image" src="https://github.com/CreativeDesigner3D/home_builder/assets/462888/760754f1-59e1-4a3a-bed4-8273c0c68040">
